// Related to validation
export const ACTION_VALIDATION_FAILED = "VALIDATION_FAILED";

// Related to Login Check.
export const ACTION_CHECK_LOGIN_STARTED = "CHECK_LOGIN_STARTED";
export const ACTION_CHECK_LOGIN_EXIST = "CHECK_LOGIN_EXIST";
export const ACTION_CHECK_LOGIN_NOTEXIST = "CHECK_LOGIN_NOTEXIST";
export const ACTION_CHECK_LOGIN_FAILED = "CHECK_LOGIN_FAILED";

// Related to Login.
export const ACTION_LOGIN_STARTED = "LOGIN_STARTED";
export const ACTION_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ACTION_LOGIN_FAILED = "LOGIN_FAILED";

// Related to getting athletes list
export const ACTION_GET_ATHLETES_STARTED = "GET_ATHLETES_STARTED"
export const ACTION_GET_ATHLETES_SUCCESS = "GET_ATHLETES_SUCCESS"
export const ACTION_GET_ATHLETES_FAILED = "GET_ATHLETES_FAILED"

// Related to adding WOD
export const ACTION_ADD_WOD_STARTED = "ADD_WOD_STARTED"
export const ACTION_ADD_WOD_FAILED = "ADD_WOD_FAILED"
export const ACTION_ADD_WOD_SUCCESS = "ADD_WOD_SUCCESS"

// Related to adding an Athlete
export const ACTION_ADD_ATHLETE_STARTED = "ADD_ATHLETE_STARTED"
export const ACTION_ADD_ATHLETE_SUCCESS = "ADD_ATHLETE_SUCCESS"
export const ACTION_ADD_ATHLETE_FAILED = "ADD_ATHLETE_FAILED"

// Related to log out method
export const ACTION_LOGOUT_STARTED = "LOG_OUT_STARTED"
export const ACTION_LOGOUT_FAILED = "LOG_OUT_FAILED"
export const ACTION_LOGGED_OUT = "LOGGED_OUT";

// Related to getting wodList
export const ACTION_GET_WOD_STARTED = "GET_WOD_STARTED"
export const ACTION_GET_WOD_SUCCES = "GET_WOD_SUCCES"
export const ACTION_GET_WOD_FAILED = "GET_WOD_FAILED"

// Related to registrration
export const ACTION_REGISTRATION_STARTED = "REGISTRATION_STARTED"
export const ACTION_REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const ACTION_REGISTRATION_FAILED = "REGISTRATION_FAILED"
export const ACTION_CLEAR_REGISTRATION = "REGISTRATION_CLEARED"

//
export const ACTION_CHECK_ACCOUNT_NOTEXIST = "CHECK_ACCOUNT_NOTEXIST"
export const ACTION_CHECK_ACCOUNT_STARTED = "CHECK_ACCOUNT_STARTED"
export const ACTION_CHECK_ACCOUNT_FAILED = "CHECK_ACCOUNT_FAILED"
export const ACTION_CHECK_ACCOUNT_EXISTS = "CHECK_ACCOUNT_EXIST"

// related to getting program types
export const ACTION_GET_PROGRAMS_STARTED = "GET_PROGRAMS_STARTED"
export const ACTION_GET_PROGRAMS_SUCCESS = "GET_PROGRAMS_SUCCESS"
export const ACTION_GET_PROGRAMS_FAILED = "GET_PROGRAMS_FAILED"

// related to getting wod of week 
export const ACTION_GET_WEEK_WOD_STARTED = "GET_WEEK_WOD_STARTED"
export const ACTION_GET_WEEK_WOD_SUCCESS = "GET_WEEK_WOD_SUCCESS"
export const ACTION_GET_WEEK_WOD_FAILED = "GET_WEEK_WOD_FAILED"

// related to changin Password
export const ACTION_CHANGE_PASSWORD_STARTED = "CHANGE_PASSWORD_STARTED"
export const ACTION_CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const ACTION_CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED"

// related to getting workouts of week
export const ACTION_GET_WORKOUTS_STARTED = "GET_WORKOUTS_STARTED"
export const ACTION_GET_WORKOUTS_SUCCESS = "GET_WORKOUTS_SUCCESS"
export const ACTION_GET_WORKOUTS_FAILED = "GET_WORKOUTS_FAILED"

// relating to setting new password
export const ACTION_SET_PASSWORD_STARTED = "SET_PASSWORD_STARTED"
export const ACTION_SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS"
export const ACTION_SET_PASSWORD_FAILED = "SET_PASSWORD_FAILED"

// related to list gyms
export const ACTION_GET_GYMS_STARTED = "GET_GYMS_STARTTED" 
export const ACTION_GET_GYMS_SUCCESS = "GET_GYMS_SUCCESS"
export const ACTION_GET_GYMS_FAILED = "GET_GYMS_FAILED"

// related to update user
export const ACTION_UPDATE_PROFILE_STARTED = "UPDATE_PROFILE_STARTED"
export const ACTION_UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const ACTION_UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED"

//related to clear athlete list
export const ACTION_CLEAR_ATHLETE_LIST = "CLEAR_ATHLETE_LIST"

//realted to get coaches
export const ACTION_GET_COACHES_STARTED = "GET_COACHES_STARTED"
export const ACTION_GET_COACHES_SUCCESS = "GET_COACHES_SUCCESS"
export const ACTION_GET_COACHES_FAILED = "GET_COACHES_FAILED"

// related to creating workout
export const ACTION_ADD_WORKOUT_STARTED = "ADD_WORKOUT_STARTED"
export const ACTION_ADD_WORKOUT_SUCCESS = "ADD_WORKOUT_SUCCESS"
export const ACTION_ADD_WORKOUT_FAILED = "ADD_WORKOUT_FAILED"

// related to creating workout in dictionary
export const ACTION_ADD_WORKOUT_DICT_STARTED = "ADD_WORKOUT_DICT_STARTED"
export const ACTION_ADD_WORKOUT_DICT_SUCCESS = "ADD_WORKOUT_DICT_SUCCESS"
export const ACTION_ADD_WORKOUT_DICT_FAILED = "ADD_WORKOUT_DICT_FAILED"

//realted to get sections
export const ACTION_GET_SECTIONS_STARTED = "GET_SECTIONS_STARTED"
export const ACTION_GET_SECTIONS_SUCCESS = "GET_SECTIONS_SUCCESS"
export const ACTION_GET_SECTIONS_FAILED = "GET_SECTIONS_FAILED"

//realted to get components
export const ACTION_GET_COMPONENTS_STARTED = "GET_COMPONENTS_STARTED"
export const ACTION_GET_COMPONENTS_SUCCESS = "GET_COMPONENTS_SUCCESS"
export const ACTION_GET_COMPONENTS_FAILED = "GET_COMPONENTS_FAILED"

//related to creaiting new section
export const ACTION_CREATE_SECTION_STARTED = "CREATE_SECTION_STARTED"
export const ACTION_CREATE_SECTION_SUCCESS = "CREATE_SECTION_SUCCESS"
export const ACTION_CREATE_SECTION_FAILED = "CREATE_SECTION_FAILED"

//related to adding component
export const ACTION_ADD_COMPONENT_STARTED = "ADD_COMPONENT_STARTED"
export const ACTION_ADD_COMPONENT_SUCCESS = "ADD_COMPONENT_SUCCESS"
export const ACTION_ADD_COMPONENT_FAILED = "ADD_COMPONENT_FAILED"

// related to clear everything
export const ACTION_CLEAR_ALL = "CLEAR_ALL"

//realted to fillWod
export const ACTION_FILL_WOD_STARTED = "FILL_WOD_STARTED"
export const ACTION_FILL_WOD_SUCCESS = "FILL_WOD_SUCCESS"
export const ACTION_FILL_WOD_FAILED = "FILL_WOD_FAILED"

//
export const ACTION_CLEAR_WOD_CREATED = "CLEAR_WOD_CREATED"

// 
export const ACTION_UPDATE_WORKOUT_STARTED = "UPDATE_WORKOUT_STARTED"
export const ACTION_UPDATE_WORKOUT_FAILED = "UPDATE_WORKOUT_FAILED"
export const ACTION_UPDATE_WORKOUT_SUCCESS= "UPDATE_WORKOUT_SUCCESS"

// 
export const ACTION_UPDATE_WORKOUT_DICT_STARTED = "UPDATE_WORKOUT_DICT_STARTED"
export const ACTION_UPDATE_WORKOUT_DICT_FAILED = "UPDATE_WORKOUT_DICT_FAILED"
export const ACTION_UPDATE_WORKOUT_DICT_SUCCESS= "UPDATE_WORKOUT_DICT_SUCCESS"

//
export const ACTION_LIST_CONSTRUCTORS_STARTED = "LIST_CONSTRUCTORS_STARTED"
export const ACTION_LIST_CONSTRUCTORS_FAILED = "LIST_CONSTRUCTORS_FAILED"
export const ACTION_LIST_CONSTRUCTORS_SUCCESS= "LIST_CONSTRUCTORS_SUCCESS"

//
export const ACTION_GET_SCORE_TYPES_STARTED = "GET_SCORE_TYPES_STARTED"
export const ACTION_GET_SCORE_TYPES_FAILED = "GET_SCORE_TYPES_FAILED"
export const ACTION_GET_SCORE_TYPES_SUCCESS= "GET_SCORE_TYPES_SUCCESS"

//
export const ACTION_GET_WORKOUTS_FROM_DICT_STARTED = "GET_WORKOUTS_FROM_DICT_STARTED"
export const ACTION_GET_WORKOUTS_FROM_DICT_FAILED = "GET_WORKOUTS_FROM_DICT_FAILED"
export const ACTION_GET_WORKOUTS_FROM_DICT_SUCCESS= "GET_WORKOUTS_FROM_DICT_SUCCESS"

//
export const ACTION_DELETE_WORKOUTS_STARTED = "DELETE_WORKOUTS_STARTED"
export const ACTION_DELETE_WORKOUTS_FAILED = "DELETE_WORKOUTS_FAILED"
export const ACTION_DELETE_WORKOUTS_SUCCESS= "DELETE_WORKOUTS_SUCCESS"

//
export const ACTION_DELETE_WORKOUTS_DICT_STARTED = "DELETE_WORKOUTS_DICT_STARTED"
export const ACTION_DELETE_WORKOUTS_DICT_FAILED = "DELETE_WORKOUTS_DICT_FAILED"
export const ACTION_DELETE_WORKOUTS_DICT_SUCCESS= "DELETE_WORKOUTS_DICT_SUCCESS"

//
export const ACTION_SIGN_FOR_WORKOUT_STARTED = "SIGN_FOR_WORKOUT_STARTED"
export const ACTION_SIGN_FOR_WORKOUT_FAILED = "SIGN_FOR_WORKOUT_FAILED"
export const ACTION_SIGN_FOR_WORKOUT_SUCCESS= "SIGN_FOR_WORKOUT_SUCCESS"

// 
export const ACTION_UPLOAD_CSV_STARTED = "UPLOAD_CSV_STARTED"
export const ACTION_UPLOAD_CSV_FAILED = "UPLOAD_CSV_FAILED"
export const ACTION_UPLOAD_CSV_SUCCESS = "UPLOAD_CSV_SUCCESS"

