// Related to validation
export const ACTION_VALIDATION_FAILED = "VALIDATION_FAILED";

// Related to Login Check.
export const ACTION_CHECK_LOGIN_STARTED = "CHECK_LOGIN_STARTED";
export const ACTION_CHECK_LOGIN_EXIST = "CHECK_LOGIN_EXIST";
export const ACTION_CHECK_LOGIN_NOTEXIST = "CHECK_LOGIN_NOTEXIST";
export const ACTION_CHECK_LOGIN_FAILED = "CHECK_LOGIN_FAILED";

// Related to Login.
export const ACTION_LOGIN_STARTED = "LOGIN_STARTED";
export const ACTION_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ACTION_LOGIN_FAILED = "LOGIN_FAILED";

// Related to getting athletes list
export const ACTION_GET_ATHLETES_STARTED = "GET_ATHLETES_STARTED"
export const ACTION_GET_ATHLETES_SUCCESS = "GET_ATHLETES_SUCCESS"
export const ACTION_GET_ATHLETES_FAILED = "GET_ATHLETES_FAILED"

// Related to adding WOD
export const ACTION_ADD_WOD_STARTED = "ADD_WOD_STARTED"
export const ACTION_ADD_WOD_FAILED = "ADD_WOD_FAILED"
export const ACTION_ADD_WOD_SUCCESS = "ADD_WOD_SUCCESS"

// Related to adding an Athlete
export const ACTION_ADD_ATHLETE_STARTED = "ADD_ATHLETE_STARTED"
export const ACTION_ADD_ATHLETE_SUCCESS = "ADD_ATHLETE_SUCCESS"
export const ACTION_ADD_ATHLETE_FAILED = "ADD_ATHLETE_FAILED"

// Related to log out method
export const ACTION_LOGOUT_STARTED = "LOG_OUT_STARTED"
export const ACTION_LOGOUT_FAILED = "LOG_OUT_FAILED"
export const ACTION_LOGGED_OUT = "LOGGED_OUT";

// Related to getting wodList
export const ACTION_GET_WOD_STARTED = "GET_WOD_STARTED"
export const ACTION_GET_WOD_SUCCES = "GET_WOD_SUCCES"
export const ACTION_GET_WOD_FAILED = "GET_WOD_FAILED"
